local wk = require("which-key")
wk.add({
  { "<leader>T", group = "Treesitter", nowait = true, remap = false },
  { "<leader>Ti", ":TSConfigInfo<cr>", desc = "Info", nowait = true, remap = false },
  { "<leader>b", group = "Buffers", nowait = true, remap = false },
  { "<leader>bb", ":b#<cr>", desc = "Previous", nowait = true, remap = false },
  { "<leader>bc", ":cclose<cr>", desc = "Close quickfix", nowait = true, remap = false },
  { "<leader>bn", ":bn<cr>", desc = "Next", nowait = true, remap = false },
  { "<leader>bp", ":bp<cr>", desc = "Previous", nowait = true, remap = false },
  { "<leader>g", group = "Git", nowait = true, remap = false },
  { "<leader>gb", ":Gitsigns blame_line<CR>", desc = "Blame", nowait = true, remap = false },
  { "<leader>gd", ":tabe % <CR> :Gitsigns diffthis<CR>", desc = "Diff", nowait = true, remap = false },
  { "<leader>gv", ":DiffviewOpen<CR>", desc = "Diff View", nowait = true, remap = false },
  { "<leader>h", ":nohlsearch<CR>", desc = "No Highlight", nowait = true, remap = false },
  { "<leader>l", group = "LSP", nowait = true, remap = false },
  { "<leader>lI", ":Mason<cr>", desc = "Installer Info", nowait = true, remap = false },
  { "<leader>lf", ":lua vim.lsp.buf.format({ async = true })<cr>", desc = "Format", nowait = true, remap = false },
  { "<leader>li", ":LspInfo<cr>", desc = "Info", nowait = true, remap = false },
  { "<leader>lr", ":lua vim.lsp.buf.rename()<cr>", desc = "Rename", nowait = true, remap = false },
  { "<leader>s", group = "Search", nowait = true, remap = false },
  { "<leader>t", group = "Diagnostics", nowait = true, remap = false },
  { "<leader>td", "<cmd>Trouble diagnostics toggle filter.buf=0<cr>", desc = "document", nowait = true, remap = false },
  { "<leader>tl", "<cmd>Trouble loclist toggle<cr>", desc = "loclist", nowait = true, remap = false },
  { "<leader>tq", "<cmd>Trouble qflist toggle<cr>", desc = "quickfix", nowait = true, remap = false },
  { "<leader>tr", "<cmd>Trouble lsp_references toggle<cr>", desc = "references", nowait = true, remap = false },
  { "<leader>tt", "<cmd>Trouble diagnostics toggle<cr>", desc = "trouble", nowait = true, remap = false },
  { "<leader>tw", "<cmd>Trouble diagnostics toggle<cr>", desc = "workspace", nowait = true, remap = false },
})
