require("_options")
require("_plugins")
require("_lsp")
require("_treesitter")
require("_whichkey")
require("_dap")
require("_null-ls")
require("_terminal")
require("_autopairs")
require("diagnostic")
require("snip")
require("snip/go")

-- vim.cmd("set notermguicolors")
vim.cmd('colorscheme base16-catppuccin-mocha')

-- vim.cmd([[hi DiffAdd      ctermfg=NONE          ctermbg=LightGray]])
-- vim.cmd([[hi DiffChange   ctermfg=NONE          ctermbg=LightGray]])
-- vim.cmd([[hi DiffText     ctermfg=NONE          ctermbg=LightGray]])
vim.cmd([[hi LineNr       ctermbg=none          guibg=none]])
vim.cmd([[hi Normal       ctermbg=none          guibg=none]])

-- important to import after colorscheme
require("_statusline")
require("_gitsigns")
